app/src/main/res/font/font_custom.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/font_style.xml
app/src/main/res/values/themes.xml

폰트 일괄 적용을 위해 파일을 추가했고 색상을 추가했습니다.
어떤 변경 사항이 있나요?

[Style] 폰트 일괄 적용 및 색상 추가

---

.idea/compiler.xml
.idea/deploymentTargetSelector.xml
.idea/misc.xml
app/build.gradle.kts
app/src/main/java/com/umc/upstyle/AdapterDay.kt
app/src/main/java/com/umc/upstyle/AdapterMonth.kt
app/src/main/java/com/umc/upstyle/BodyinfoActivity.kt
app/src/main/java/com/umc/upstyle/MyHomeFragment.kt
app/src/main/java/com/umc/upstyle/SearchFragment.kt
app/src/main/res/layout/activity_bodyinfo.xml
app/src/main/res/layout/activity_closet.xml
app/src/main/res/layout/activity_myhome.xml
app/src/main/res/layout/fragment_search.xml
app/src/main/res/layout/list_item_day.xml
app/src/main/res/layout/list_item_month.xml
app/src/main/res/values/styles_calander.xml
build.gradle.kts
settings.gradle.kts

Fix week2 yh

---

.idea/compiler.xml
app/.idea/.gitignore
app/.idea/caches/deviceStreaming.xml
app/.idea/gradle.xml
app/.idea/migrations.xml
app/.idea/misc.xml
app/.idea/runConfigurations.xml
app/.idea/vcs.xml
app/build.gradle.kts
app/src/main/java/com/umc/upstyle/CategoryFragment.kt
app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
app/src/main/res/layout/activity_today_ootd.xml

TodayOotdFragment 날짜 추가, 자잘한 오류 수정
어떤 변경 사항이 있나요?
- [x ] 새로운 기능 추가
- [x ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ x] 코드가 정상적으로 컴파일되나요?
- [x ] merge할 브랜치의 위치를 확인했나요?
- [x ] Label을 지정했나요?

Fix: TodayOotdFragment 날짜 추가, 자잘한 오류 수정

---

app/src/main/res/navigation/nav_graph.xml

nav graph 수정
post detail 화면 관련 액션 추가 및 아규먼트 추가 
어떤 변경 사항이 있나요?

Fix: Nav 오류 수정

---

app/src/main/java/com/umc/upstyle/AccountFragment.kt
app/src/main/java/com/umc/upstyle/CategoryFragment.kt
app/src/main/java/com/umc/upstyle/LogoutPopupDialog.kt
app/src/main/java/com/umc/upstyle/MyProfileFragment.kt
app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
app/src/main/java/com/umc/upstyle/WebViewFragment.kt
app/src/main/res/drawable/ic_namechk_gray.xml
app/src/main/res/drawable/ic_namechk_red.xml
app/src/main/res/drawable/ic_namechk_white.xml
app/src/main/res/layout/fragment_account.xml
app/src/main/res/layout/fragment_my_profile.xml
app/src/main/res/layout/fragment_web_view.xml
app/src/main/res/layout/logout_popup.xml
app/src/main/res/navigation/nav_graph.xml

계정 화면, 기능 구현 완료
어떤 변경 사항이 있나요?

Feature: 계정 화면, 기능 구현 완료

---

.idea/gradle.xml
app/src/main/java/com/umc/upstyle/BookmarkFragment.kt
app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
app/src/main/res/layout/recycler_item_bookmark.xml
app/src/main/res/layout/recycler_item_closet.xml
app/src/main/res/layout/recycler_item_load.xml
app/src/main/res/layout/recycler_item_result.xml
app/src/main/res/layout/recycler_item_search.xml

사진등록 글자 관련 수정 북마크 레이아웃 수정

---

app/src/main/res/drawable/bg_2a2a2a_gray.xml
app/src/main/res/layout/activity_category.xml
app/src/main/res/layout/activity_color.xml
app/src/main/res/layout/activity_fit.xml
app/src/main/res/layout/fragment_create_vote.xml
app/src/main/res/layout/fragment_etc.xml

Fix: 카테고리 여백 수정 및 글쓰기 사진 등록 버튼 추가

---

app/src/main/java/com/umc/upstyle/ChatFragment.kt
app/src/main/java/com/umc/upstyle/CreateRequestFragment.kt
app/src/main/java/com/umc/upstyle/CreateVoteFragment.kt
app/src/main/java/com/umc/upstyle/LoadCategoryFragment.kt
app/src/main/java/com/umc/upstyle/LoadItemFragment.kt
app/src/main/java/com/umc/upstyle/VotePopupDialog.kt
app/src/main/res/drawable/ic_close.xml
app/src/main/res/layout/fragment_create_request.xml
app/src/main/res/layout/fragment_create_vote.xml
app/src/main/res/layout/fragment_load_category.xml
app/src/main/res/layout/photo_popup.xml
app/src/main/res/layout/vote_popup.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/values/styles_login.xml

글쓰기 화면에 사진 첨부&아이템 로드 가능하게 수정했습니다
어떤 변경 사항이 있나요?

Feat: 글쓰기 화면 기능 추가

---

app/src/main/java/com/umc/upstyle/AdapterDay.kt
app/src/main/java/com/umc/upstyle/ClosetFragment.kt
app/src/main/java/com/umc/upstyle/ClosetItemFragment.kt
app/src/main/java/com/umc/upstyle/MyHomeFragment.kt
app/src/main/java/com/umc/upstyle/OotdDetailFragment.kt
app/src/main/java/com/umc/upstyle/PostDetailFragment.kt
app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
app/src/main/java/com/umc/upstyle/ViewVoteFragment.kt
app/src/main/java/com/umc/upstyle/data/model/VoteDetailResponse.kt
app/src/main/java/com/umc/upstyle/data/network/RetrofitClient.kt
app/src/main/java/com/umc/upstyle/data/network/VoteService.kt
app/src/main/res/layout/fragment_post_detail.xml
app/src/main/res/layout/fragment_view_vote.xml
app/src/main/res/navigation/nav_graph.xml

Feat: Post Detail Fragment

---

app/build.gradle.kts
app/src/main/java/com/umc/upstyle/BookmarkOotdFragment.kt
app/src/main/java/com/umc/upstyle/ClosetItemFragment.kt
app/src/main/java/com/umc/upstyle/Item_load.kt
app/src/main/java/com/umc/upstyle/LoadItemFragment.kt
app/src/main/java/com/umc/upstyle/RecyclerAdapter_Closet.kt
app/src/main/java/com/umc/upstyle/RecyclerAdapter_Load.kt
app/src/main/java/com/umc/upstyle/SearchItemFragment.kt
app/src/main/java/com/umc/upstyle/data/model/BookmarkRequest.kt
app/src/main/java/com/umc/upstyle/data/model/BookmarkResponse.kt
app/src/main/java/com/umc/upstyle/data/model/ClosetCategoryResponse.kt
app/src/main/java/com/umc/upstyle/data/model/ClothPreview.kt
app/src/main/java/com/umc/upstyle/data/network/Apiservice.kt

 로드 아이템, 클로우젯 아이템 수정

---

app/src/main/java/com/umc/upstyle/RecyclerAdapter_Result.kt
app/src/main/java/com/umc/upstyle/SearchItemFragment.kt
app/src/main/java/com/umc/upstyle/SearchResultFragment.kt
app/src/main/java/com/umc/upstyle/data/model/ClothPreview.kt
app/src/main/java/com/umc/upstyle/data/model/ClothesCategoryResponse.kt
app/src/main/java/com/umc/upstyle/data/model/OOTDPreview.kt
app/src/main/java/com/umc/upstyle/data/network/Apiservice.kt
app/src/main/res/navigation/nav_graph.xml

searchItem 수정

---

.idea/gradle.xml
app/build.gradle.kts
app/src/main/java/com/umc/upstyle/BottomSheetViewFragment.kt
app/src/main/java/com/umc/upstyle/CodiBottomSheetDialogFragment.kt
app/src/main/java/com/umc/upstyle/CreateRequestFragment.kt
app/src/main/java/com/umc/upstyle/CreateVoteFragment.kt
app/src/main/java/com/umc/upstyle/LoadCategoryFragment.kt
app/src/main/java/com/umc/upstyle/LoadItemFragment.kt
app/src/main/java/com/umc/upstyle/MyHomeFragment.kt
app/src/main/java/com/umc/upstyle/RequestDetailFragment.kt
app/src/main/java/com/umc/upstyle/ResponseFragment.kt
app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
app/src/main/java/com/umc/upstyle/data/model/RequestResponse.kt
app/src/main/java/com/umc/upstyle/data/network/RequestService.kt
app/src/main/java/com/umc/upstyle/utils/CategoryUtil.kt
app/src/main/res/layout/activity_myhome.xml
app/src/main/res/layout/fragment_codi_bottom_sheet_dialog.xml
app/src/main/res/layout/fragment_load_category.xml
app/src/main/res/layout/fragment_request_detail.xml
app/src/main/res/layout/list_item_day.xml
gradle/libs.versions.toml

코디 요청 응답 보기+댓글 등록 기능 구현+불필요한 코드 삭제

---

app/src/main/java/com/umc/upstyle/CreateVoteFragment.kt
app/src/main/java/com/umc/upstyle/LoadCategoryFragment.kt
app/src/main/java/com/umc/upstyle/PostAdapter.kt
app/src/main/java/com/umc/upstyle/ResponseFragment.kt
app/src/main/java/com/umc/upstyle/VoteFragment.kt
app/src/main/java/com/umc/upstyle/VoteItemAdapter.kt
app/src/main/java/com/umc/upstyle/data/model/Vote.kt
app/src/main/java/com/umc/upstyle/data/model/VoteItem.kt
app/src/main/java/com/umc/upstyle/data/network/VoteService.kt
app/src/main/java/com/umc/upstyle/data/viewmodel/CategoryViewModel.kt
app/src/main/java/com/umc/upstyle/data/viewmodel/PostViewModel.kt
app/src/main/java/com/umc/upstyle/data/viewmodel/ResponseViewModel.kt
app/src/main/res/layout/fragment_create_request.xml
app/src/main/res/layout/fragment_create_vote.xml
app/src/main/res/layout/fragment_post_detail.xml
app/src/main/res/layout/item_post.xml
app/src/main/res/layout/item_request.xml
app/src/main/res/layout/item_vote.xml
app/src/main/res/navigation/nav_graph.xml

투표 글 작성 기능 구현 api 연결까지 완료🥹

---

app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
app/src/main/res/layout/activity_today_ootd.xml

Feat: OOTD 등록화면 로딩창 추가

---

app/src/main/java/com/umc/upstyle/BookmarkOotdFragment.kt
app/src/main/java/com/umc/upstyle/Item_result.kt
app/src/main/java/com/umc/upstyle/Item_search.kt
app/src/main/java/com/umc/upstyle/RecyclerAdapter_Result.kt
app/src/main/java/com/umc/upstyle/RecyclerAdapter_Search.kt
app/src/main/java/com/umc/upstyle/RequestDetailFragment.kt
app/src/main/java/com/umc/upstyle/SearchResultFragment.kt
app/src/main/java/com/umc/upstyle/data/model/Cloth.kt
app/src/main/java/com/umc/upstyle/data/model/ClothPreview.kt
app/src/main/java/com/umc/upstyle/data/model/ClothesCategoryResponse.kt
app/src/main/java/com/umc/upstyle/data/model/Ootd.kt
app/src/main/java/com/umc/upstyle/data/model/User.kt
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/fragment_bookmark_ootd.xml
app/src/main/res/layout/fragment_search_result.xml

코딩너무오래해서심장이두근거리네요...ㅋㅋㅋ
어떤 변경 사항이 있나요?

Feat: SearchItem -> SearchResult -> BookmarkOotd 구현

---

app/src/main/java/com/umc/upstyle/BookmarkFragment.kt
app/src/main/java/com/umc/upstyle/BookmarkOotdFragment.kt
app/src/main/java/com/umc/upstyle/data/model/BookmarkRequest.kt
app/src/main/java/com/umc/upstyle/data/model/BookmarkResponse.kt
app/src/main/java/com/umc/upstyle/data/network/Apiservice.kt
app/src/main/res/navigation/nav_graph.xml

류지님 브랜치 북마크 오오티디 연동

---

app/src/main/res/layout/fragment_bookmark_ootd.xml

Design: 백버튼 간격 수정

---

app/src/main/java/com/umc/upstyle/BookmarkFragment.kt
app/src/main/java/com/umc/upstyle/BookmarkOotdFragment.kt
app/src/main/java/com/umc/upstyle/data/model/BookmarkRequest.kt
app/src/main/java/com/umc/upstyle/data/network/Apiservice.kt
app/src/main/res/layout/fragment_bookmark_ootd.xml
app/src/main/res/layout/recycler_item_bookmark.xml

Feat: 북마크 관련 api 연결 수정

---

app/src/main/java/com/umc/upstyle/FilterViewModel.kt
app/src/main/java/com/umc/upstyle/Item_search.kt
app/src/main/java/com/umc/upstyle/SearchCategoryFragment.kt
app/src/main/java/com/umc/upstyle/SearchColorFragment.kt
app/src/main/java/com/umc/upstyle/SearchFilterFragment.kt
app/src/main/java/com/umc/upstyle/SearchFilterOotdFragment.kt
app/src/main/java/com/umc/upstyle/SearchFitSizeFragment.kt
app/src/main/java/com/umc/upstyle/SearchFragment.kt
app/src/main/java/com/umc/upstyle/SearchSubcategoryFragment.kt
app/src/main/java/com/umc/upstyle/SharedPreferencesUtils.kt
app/src/main/java/com/umc/upstyle/data/model/ClothPreview.kt
app/src/main/java/com/umc/upstyle/data/network/Apiservice.kt
app/src/main/java/com/umc/upstyle/utils/CategoryUtil.kt
app/src/main/res/layout/fragment_search_filter_ootd.xml
app/src/main/res/layout/fragment_search_subcategory.xml
app/src/main/res/navigation/nav_graph.xml

Feat: 검색_사용자 옷장 기반 검색(ootd제외 구현)

---

app/src/main/java/com/umc/upstyle/FilterViewModel.kt
app/src/main/java/com/umc/upstyle/SearchCategoryFragment.kt
app/src/main/java/com/umc/upstyle/SearchColorFragment.kt
app/src/main/java/com/umc/upstyle/SearchFilterFragment.kt
app/src/main/java/com/umc/upstyle/SearchFitSizeFragment.kt
app/src/main/java/com/umc/upstyle/SearchFragment.kt
app/src/main/java/com/umc/upstyle/SearchSubcategoryFragment.kt
app/src/main/res/layout/fragment_search_color.xml

Fix: 검색창(필터창)을 이용한 검색_필터링 오류 수정
